[package]
name = "zome"
version ="0.3.1-rc"
edition = "2021"

[dependencies]
hdk = "0.3.1-rc"

[lib]
crate-type = ["cdylib", "rlib"]
name = "my_zome"

[dev-dependencies]
fixt = "0.3.1-rc"
futures = { version = "0.3.1", default-features = false }
hdk = { version = "0.3.1-rc", features = ["encoding", "test_utils"] }
holochain = { version = "0.3.1-rc", features = ["test_utils"] }
