[package]
name = "hrl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
hdk = "0.3.1-rc"
holo_hash = { version = "0.3.1-rc", features = ["encoding"] }
