[package]
name = "hrl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
hdk = { workspace = true }
holo_hash = { workspace = true, features = ["encoding"] }
