[package]
name = "file_tree_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
ignore = "0.4"
build-fs-tree = "0.4.0"
thiserror = "1.0.22"
include_dir = "0.7.3"
