name: "test-nix-infra"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  linux-build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - name: Build zomes
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_TOKEN_HOLOCHAIN_OPEN_DEV }}"
        run: |
          cd ./nix/fixtures/module-repo
          nix flake update
          cachix watch-exec holochain-open-dev -- nix build -L .#my_zome
          sha256sum result

  macos-just-get-from-cache:
    needs: linux-build-and-cache
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - name: Install coreutils for macOS
        run: brew install coreutils

      - name: Build zomes
        run: |
          cd ./nix/fixtures/module-repo
          nix flake update
          nix build -L .#my_zome
          sha256sum result
